# Generated by Django 6.0.2 on 2026-03-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_achievement_created_at_achievement_proof_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='created_at',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(blank=True, default='Not Assigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
