# Generated by Django 6.0.3 on 2026-04-26 18:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_stall_stallbooking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='registered_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stall',
            name='booked_slots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stall',
            name='total_slots',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='stallbooking',
            unique_together={('user', 'stall')},
        ),
    ]
