# Generated by Django 6.0.3 on 2026-04-27 06:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_activity_capacity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='event_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='registered_count',
            new_name='filled_seats',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='capacity',
            new_name='total_seats',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='registered_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='student',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('user', 'activity')},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='last_date',
        ),
        migrations.AddField(
            model_name='registration',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlist', 'Waitlist')], default='pending', max_length=10),
        ),
    ]
