# Generated by Django 6.0.3 on 2026-04-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_rename_event_date_activity_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('Cultural', 'Cultural'), ('Sports', 'Sports'), ('Technical', 'Technical'), ('NCC & Outreach', 'NCC & Outreach'), ('College Fest', 'College Fest')], max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='filled_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='total_seats',
            field=models.IntegerField(),
        ),
    ]
